version: '2'

services:
  react:
    build:
      context: my-app
      dockerfile: Dockerfile
    container_name: react-web
    networks:
      - docker-network
    ports:
      - "8081:3000"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    hostname: api
    ports:
      - "8082:8080"
    networks:
      - docker-network
    

  
  # web:
  #   build:
  #     context: web
  #     dockerfile: Dockerfile
  #   container_name: nginx_web
  #   networks:
  #     - docker-network
  #   ports:
  #     - "8081:80"

networks:
  docker-network:
    external: true