version: '2'

services:
  react:
    build:
      context: my-app
      dockerfile: Dockerfile
    container_name: react-web
    networks:
      - docker-network
    ports:
      - "8081:3000"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    hostname: api
    restart: always
    ports:
      - "8082:8080"
    networks:
      - docker-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    build:
      context: db
      dockerfile: Dockerfile
    hostname: db
    networks:
      - docker-network
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    
    

    
  # web:
  #   build:
  #     context: web
  #     dockerfile: Dockerfile
  #   container_name: nginx_web
  #   networks:
  #     - docker-network
  #   ports:
  #     - "8081:80"

networks:
  docker-network:
    external: true